### ISSUE TITLE
Regex fails to match certain valid URLs

### ISSUE THREAD

**Issue by DSRAdr** [thecodeofdaniel/UdemySpeedup#1]
The project uses this regex pattern on the current page's URL to determine whether to activate.
https://github.com/thecodeofdaniel/UdemySpeedup/blob/7743c8fa628c989bcbf4ca33936cc051fcef8e7f/src/global.js#L8-L16

Whilst it works in most situations, it isn't actually exhaustive. Specifically, I noticed after reading a Q&A that the extension stopped working.
This was because while previously the URL had been
`https://www.udemy.com/course/foo/learn/lecture/bar`,
after viewing a Q&A, it had become
`https://www.udemy.com/course/foo/learn/lecture/bar#questions/baz`,
where the addition of a further `/` caused it to no longer match.

Assuming there are no other valid path segments, consider changing the regex pattern to
```regex
/^https:\/\/www\.udemy\.com\/course\/[^\/]+\/learn\/lecture\/(?:|\d+#questions\/)[^\/]+$/
```
or maybe just drop the last `/` check.

**Comment by thecodeofdaniel** [comment]
Ah I see, thanks for the detailed explanation! I just dropped the last `/` check as you mentioned. So `bar` will be everything after the `https://www.udemy.com/course/foo/learn/lecture/` URL.  

Seems like the issue is fixed now, but if possible, run the extension on your machine and let me know if the issue persists. Otherwise, I'll go ahead and publish this new version.

**Comment by DSRAdr** [comment]
Can confirm it does seem to work. 👍

**Comment by thecodeofdaniel** [comment]
The new version is up. Thanks for the help!
